"use client";

import { useState } from "react";
import { CheckCircle, Clock, Mail } from "lucide-react";

export default function TasksPage() {
  const [tasks, setTasks] = useState([
    {
      id: 1,
      title: "Follow up with client on proposal",
      source: "Email from David Johnson",
      due: "Today",
      done: false,
    },
    {
      id: 2,
      title: "Review HR policy update",
      source: "Email from HR Team",
      due: "Tomorrow",
      done: true,
    },
  ]);

  const toggleTask = (id: number) => {
    setTasks((prev) =>
      prev.map((task) =>
        task.id === id ? { ...task, done: !task.done } : task
      )
    );
  };

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <h1 className="text-2xl font-semibold mb-4 text-gray-800">✅ Tasks</h1>
      <p className="text-gray-500 text-sm mb-6">
        Automatically generated by WhisprAI from your messages and emails.
      </p>

      <div className="space-y-4">
        {tasks.map((task) => (
          <div
            key={task.id}
            className="bg-white rounded-xl p-4 shadow-sm border flex justify-between items-center hover:shadow-md transition"
          >
            <div>
              <p
                className={`font-medium ${
                  task.done ? "line-through text-gray-400" : "text-gray-800"
                }`}
              >
                {task.title}
              </p>
              <div className="flex items-center space-x-2 text-sm text-gray-500 mt-1">
                <Mail className="w-4 h-4" />
                <span>{task.source}</span>
                <Clock className="w-4 h-4 ml-3" />
                <span>{task.due}</span>
              </div>
            </div>

            <button
              onClick={() => toggleTask(task.id)}
              className={`text-sm font-semibold px-3 py-1 rounded-full ${
                task.done
                  ? "bg-green-100 text-green-700"
                  : "bg-gray-100 text-gray-700 hover:bg-green-50"
              }`}
            >
              {task.done ? "Done" : "Mark Done"}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
